ui/Gruntfile.js, ui/package.json
We are using the harmony branch of `grunt-contrib-uglify` in the ui. The name of the package was changed to `grunt-contrib-uglify-es` (only in this branch: https://github.com/gruntjs/grunt-contrib-uglify/commit/ccb95a70cad6a4e9e902d3bd5d0e38a4de09a1e1) and it won't install at the moment. 
The changes in this PR make the `grunt build` task work with uglify-es.
Also relevant: https://github.com/gruntjs/grunt-contrib-uglify/issues/499
(a separate packate `grunt-contrib-uglify-es` will be available soon)
=> harmony branch of uglify renamed to uglify-es

installer/vars/mobile-control-panel.yml
By default oc 3.7.0 will be installed. However we are overwriting
this information with an out-of-date data structure containing information
such as the oc version and a checksum.. This is resulting
in any users who do not already have oc cached locally or installed
to experience an error with trying to access the data structure.
This change removes the overridden data structure so that the default
data structure can be used and install oc 3.7.0.
Resolves https://github.com/aerogear/mobile-core/issues/1
Remove a no longer needed variable override.
=> Remove unneeded oc install information

installer/install.sh
Ansible installer is required to run every time we need to start new mcp server. Every time users will need to pass their own password. This change will use globally defined username and password if user will skip this fields
=> Add global dockerhub variables

installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh
I had experienced problems with ansible broker when using version provided by install script. 
It looks like team fixed couple issues and recent release version has change done by @matzew 
https://github.com/openshift/ansible-service-broker/pull/601
See tags: https://hub.docker.com/r/ansibleplaybookbundle/origin-ansible-service-broker/tags/
I have been using this today and it seems to work. I might miss some details about this so feel free to close this PR. Sharing this for wider group as this may help you guys to resolve problems with push (when you use latest abp). 
ping @pb82 @maleck13 @matzew @aidenkeating
=> Update ansible service  broker versions

README.adoc, ui/package-lock.json
Some folks running into local dep issues - these errors are guided through in `install.sh`, so updating the README to refer to this script instead for quick setup.
Also checked in a copy of `package-lock.json`
=> Refer to install.sh in README for quick setup guide

docs/walkthroughs/developing-apbs-locally.adoc
Steps were used to setup https://hub.docker.com/r/aerogearcatalog/metrics-apb/
=> 📝 Add steps for setting up a docker automated build

installer/install.sh, installer/requirements.yml
Currently when we install roles in the install script they will not be overwritten with updated roles. Instead the old role will remain.
This fix specifies the version in the requirements.yml. By just adding the version alone was not enough to update the roles, adding --force tag, forces the update if an update is required, deleting the old role and installing the updated role in its place.
@aidenkeating
=> Ansible Galaxy Roles Updating

installer/roles/ansible-service-broker-setup/defaults/main.yml, installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh, installer/roles/ansible-service-broker-setup/tasks/main.yml, installer/roles/setup-openshift-admin-user/tasks/main.yml
Re-running the ansible service broker setup playbook results in errors (project already exists).  Also re-running after the ASB has been removed or is marked for termination will result in errors because there is left over resources (cluster role bindings, cluster roles and cluster service broker) after deleting the `ansible-service-broker` project or namespace.
Implement a deprovision task that removes related resources to the ansible service broker.
This task is run only when the `ansible-service-broker` namespace is not found. Not found meaning either A) the ASB was never provisioned (first time provisioning), B)  the ASB was marked for termination (`oc get namespace ansible-service-broker` responds with a `not found`) or C) the ASB has been deleted.
This should improve the idempotency …
=> Aerogear 1823 - Implement deprovision task for ansible service broker

installer/roles/setup-openshift-admin-user/tasks/main.yml
At the moment these additional permissions need to be added every time a new cluster created if you intend on working with APBs locally (pushing, bootstrapping, relisting etc.)
It would be nice to get this fixed!
=> fix: add required permissions to admin user for pushing apbs

Jenkinsfile
Currently we are only runing -short tests in our mobile-cli PRs. We should be doing the same in mobile-core.
=> Changing the integration tests to use test.short flag

Jenkinsfile
If there is a problem with the build, the slave should hang around for us to be able to investigate the failure. The user is able to dispose of it.
=> Added cancellable timeout on failure, to leave the slave hanging

docs/walkthroughs/developing-apbs-locally.adoc
Document the required & optional bits for a service APB.
Add some information about making mobile service APB's.
Specifics to mention
=> added mobile service specific apb info

docs/walkthroughs/provision-keycloak-apb.adoc
Added the link of the video demonstrating how to use a shared keycloak service and how to link another keycloak service to it to the keycloak apb documentation. 
Demo video is produced by the following JIRA - https://issues.jboss.org/browse/AEROGEAR-2171
=> Add link of shared keycloak service demo video

docs/walkthroughs/developing-apbs-locally.adoc
The local apb development process we are describing seems to be out of date with the official apb development process and documentation. 
Point the mobile apb developers to the ansible playbook bundle documentation for setup instructions for the apb developer tools. If you install the apb tools locally, or use the upstream containerised installation of the apb tools, local development can be achieved without the need for pushing to an external docker registry.
-
=> AEROGEAR-2491 - Update apb local development docs

installer/roles/create-mobile-client-crd/files/mobile-client-crd.yaml
These patterns are autogenerating a strange required params field that cannot be satisfied. Removing them for now, to unblock other work, until we properly understand how these function.
=> remove patterns from CRD

installer/roles/create-mobile-client-crd/files/mobile-client-crd.yaml
Xamarin client type creation is failing when using minishift.
Added "xamarin" client type in mobile-client-crd.yaml
=> added xamarin client type

docs/walkthroughs/developing-apbs-locally.adoc
There is an issue with setting an APB to be bindable without encoding any binding fields during provision. The provision tasks gives no errors and the task completes successfully but the provision still fails. This needs to be added to the documentation for developing apbs for awareness until this issue has been resolved.
https://github.com/openshift/ansible-service-broker/issues/847
=> add information on provision issue when apb is set to be bindable

installer/roles/create-mobile-client-crd/files/mobile-client-crd.yaml
https://issues.jboss.org/browse/AEROGEAR-2602
- `oc delete -f mobile-client-crd.yaml`
- `oc create -f https://raw.githubusercontent.com/witmicko/mobile-core/56c53c5a1e0eef7f9b5b60ffcfabd5bdf587309c/installer/roles/create-mobile-client-crd/files/mobile-client-crd.yaml`
- `minishift openshift restart`
- Add mobile client to your project
- Resources > other > mobile client > actions > edit YAML
- add `  dmzUrl: invalidUrl` at the bottom of mobile crd > should get a validation error on save
- try different urls:
`www.hello.com.ok`
`http://www.hello.com.ok`
`http://www.hello.com.ok/ersdfs`
`http://www.hello.com.ok/ersdfs?dfd=dfgd@s=1`
`http://www.hello.com:81/index.html`
=> AEROGEAR-2602 add dmz url prperty to MAR CRD

installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh
Fot the UPS APB we rely on a change that is only available in this more recent version of the asb (https://github.com/openshift/ansible-service-broker/pull/883). There is no tagged release > 1.1 yet so i picked the latest sprint tag for now.
Openshift 3.10 will include the right ASB by default.
Update ASB version. This new version adds a new parameter to the bind role, the ID of the service binding. We want to use that to trigger an unbind via an external action.
It looks like this update is not required for the Minishift addon because it defaults to the `latest` tag of ASB (https://github.com/aerogear/minishift-mobilecore-addon/blob/master/mobile-core.addon#L29 ). @philbrookes can you confirm?
=> update to latest asb

docs/walkthroughs/installing-mobile-cli.adoc
Add a document to the mobile-core repo that details how to install the mobile CLI
[AEROGEAR-2409](https://issues.jboss.org/browse/AEROGEAR-2409)
=> [AEROGEAR-2409] Add docs for installing the Mobile CLI

Jenkinsfile
As stated in https://issues.jboss.org/browse/RHMAP-20431
Running of the ansible stays.
The slave will stay around only if "leave slave on failure is applied".
=> Removing integration tests from the end of PR-check

docs/walkthroughs/provision-mobile-ci-cd.adoc
- Removes aerogear digger link from overview section
- Adds a link to the official android doc
=> Cicd doc fix

installer/playbook.yml, installer/roles/output-oc-cluster-status/tasks/main.yml
add oc cluster status to end of output.
add oc cluster status to end of output.
```
16:25 $ ./installer/install.sh 
__  __  ____ ____
|  \/  |/ ___|  _ \
| |\/| | |   | |_) |
| |  | | |___|  __/
|_|  |_|\____|_|
.... <snip> .....
TASK [output-oc-cluster-status : debug] ******************************************************************************************************************************************************
ok: [localhost] => {
"msg": [
"Web console URL: https://192.168.37.1:8443/console/", 
"", 
"Config is at host directory /var/lib/origin/openshift.local.config", 
"Volumes are at host directory /var/lib/origin/openshift.local.volumes", 
"Persistent volumes are at host directory /var/lib/origin/openshift.local.pv", 
"Data is at host directory …
```
=> add oc cluster status to end of output.

installer/install.sh
the installer immediately pauses when run. This was due to the unneeded call for the banner.
=> removes the call to the banner function

installer/roles/patch-origin-web-console/tasks/main.yml
origin-web-console doesn't get updated when a stale image is present.
JIRA: https://issues.jboss.org/browse/AEROGEAR-3397
1. checkout these changes
2. `make clean && ./installer/install.sh`
3.  login as admin
4. ensure that origin-web-console config yaml has imagePullPolicy set to Always
=> set image pull policy to Always for origin-console

installer/roles/oc-cluster-up/tasks/main.yml
revert loopback change, it has broken clusters running on 192.168.* that are not on the laptops IP.
=> revert loopback change

installer/install.sh, installer/requirements.yml
Was getting this error still (master & 1.0.0 tag of mobile-core):
```
[WARNING]: - andrewrothstein.alpine_glibc_shim was NOT installed successfully: - sorry, andrewrothstein.alpine_glibc_shim was not
found on https://galaxy.ansible.com.
```
even after the changes in https://github.com/aerogear/mobile-core/pull/119
From reading the latest updates on: https://github.com/ansible/galaxy/issues/775, it looks as though ansible galaxy have fixed this.
This change:
- reverts https://github.com/aerogear/mobile-core/pull/119 (should no longer be needed)
- Update ansible version check to something more recent (2.6)
=> Revert dependency fix

installer/install.sh
Issue: https://github.com/aerogear/mobile-core/issues/173
Check if the Wildcard DNS input is valid.
- [] TODO
Following local tests.
=> fix(installer): Installer fails when wildcard DNS suffix is specified as a blank string, ie

History.md, installer/install.sh
Issue: https://github.com/aerogear/mobile-core/issues/137
Just add a link of python doc since to install python is required to follow a procedure according to SO used. 
- [] TODO
Following local test to check the message/change.
=> fix(installer): Message when python is not installed

installer/install.sh
The min versions are repeated in many places in the install.sh script which is not a good practice and it is susceptible to errors. 
Just centralize the versions by global static variables. 
- [] TODO
To test it is just required to run the installer. 
Following local test.
=> task(centralize min version): centralize min versions

installer/install.sh
Issue: https://github.com/aerogear/mobile-core/issues/132
* Run 'oc cluster up' before ansible tasks in order to check it. 
* Add spinner in the script in order to inform that the action is in progress
* If  'oc cluster up' has an error show the error and suggest the link of the docs to solve it
* If the error is because of it already is up then the checked need to pass to
* Go to the local docker >> preferences and remove the o --insecure-registry.
* Then,  the following error which is expected if the oc cluster up command is executed. 
* Now executed the script `./installer/install.sh ` the following error message is expected. 
* When the cluster has an error ( --insecure-registry not setup )
* When the cluster is already up
* When the clsuter is down and all is properly setup
=> fix(installer): Add 'oc cluster up' validation

installer/install.sh
Issue: https://github.com/aerogear/mobile-core/issues/134
* Apply a similar standard that we we have for our fh tools regards the default values
* Apply hidden password
* Show the default values which will be added. 
- [] TODO
Following local tests. 
`$export DOCKERHUB_USERNAME=<value>`
`$export DOCKERHUB_PASSWORD=<value>`
=> fix(installer): Default values standard and making clear Docker input values

docs/walkthroughs/local-setup.adoc, installer/install.sh
Issue: https://github.com/aerogear/mobile-core/issues/136
* Installer output does not make clear which password is required
* The root pwd is requested more than once 
* Remove the param `--ask-become-pass` in ansible task and instead of it executed the tasks as root, since the pwd was already asked in the before action.
* Change the wording/message in order to make clear that is required the sudo/root pwd. 
Following its result. 
```
Performing clean and running the installer ...
You will be asked for your System Admin Password(root/sudo).
Password:
```
- [] TODO
Following the FULL local test. 
````
cmacedo@camilas-MBP ~/mobile-core (ISSUE_136) $ ./installer/install.sh 
Checking Docker exists
✓ Docker check passed.
Checking Docker is running
✓ Docker check passed.
Checking Docker …
```
=> fix(installer): Installer output does not make clear which password is required and ask more than once for this information

installer/roles/ansible-service-broker-setup/meta/main.yml, installer/roles/oc-cluster-up/meta/main.yml, installer/roles/template-service-broker-setup/meta/main.yml
* Support all Fedora versions
* Issues: https://github.com/aerogear/mobile-core/issues/140 and https://github.com/aerogear/mobile-core/issues/110 and https://github.com/aerogear/mobile-docs/issues/345
Some roles are not covering the newer Fedora versions.
- [] TODO
To test it is required to try to install in a Fedora 27 and/or 28.
=> Adding support/roles to run all versions of Fedora

installer/install.sh
Issue https://github.com/aerogear/mobile-core/issues/205
Fix to get the result of the ansible scripts 
To show the properly msg when it fails and the process was not executed in debug mode
* Checking if the ansible has failures
* Fixing the place to get the result of the correct process
* Run it in a Fedora without the lib `libselinux-python` installed 
* See if it will finish with the ERROR and the info to re-run it with the --debug param to get further information as follows. ( Ref scenario Issue https://github.com/aerogear/mobile-core/issues/140 )
OR
* Comment the `oc cluster up` validation into the install.sh script for don't check it (The code is [here](https://github.com/aerogear/mobile-core/blob/master/installer/install.sh#L310))
* Remove the registry configured in the docker
* …
=> fix(installer): Issue 205: Installer successfully terminates improperly when an error occurs in the Ansible script execution

installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh
I have noticed cases where this script has called this finish function in cases where everything was executed successfully and this causes the overall installer to fail. These trap features are useful for things like catching events and performing cleanups, removing files etc before exiting. In our case, it's not actually doing anything and it's unnecessary.
@ziccardi can you try this out and see if it makes any difference for you?
=> fix: remove trap from provision-ansible-service-broker.sh
