aerogear/mobile-core

docs/walkthroughs/local-setup.adoc, installer/roles/oc-cluster-up/defaults/main.yml
Improvements after following setup guide
@aidenkeating
=> Install changes

installer/install.sh
Small typo in the installer script output
@aidenkeating @david-martin
=> typo fix to installer output

docs/walkthroughs/developing-apbs-locally.adoc
image has been renamed
rename image to match actual name
=> change name of apb docker image

docs/walkthroughs/developing-apbs-locally.adoc
update for  language fixes and asciidoc syntax
=> update developing-apbs-locally.adoc with style edits

installer/install.sh
Currently we only check the version of docker, this change adds two checks, one to see if docker exists, and the other to see if docker is currently running.
@aidenkeating
=> Add extra docker checks

docs/walkthroughs/developing-apbs-locally.adoc
Original Ticket here: https://issues.jboss.org/browse/AEROGEAR-1862
=> Update APB doc to reflect new local dev workflows

docs/walkthroughs/developing-apbs-locally.adoc
=> fix(doc): fix a minor typo in apb guide

installer/roles/oc-cluster-up/defaults/main.yml
Enable MEM/CPU stats
enables MEM/CPU via existing Openshift feature for Heapster
=> Enabling Hawkular's metrics for MEM/CPU

installer/install.sh
=> fixes mini typo

installer/roles/oc-cluster-up/defaults/main.yml
latest greatest
update to recent release
=> Latest Origin

installer/requirements.yml
latest client tools
updating to latest
=> Using tool that defaults to 3.7.1, like our dependency

Jenkinsfile, installer/roles/oc-cluster-up/defaults/main.yml, installer/roles/oc-cluster-up/tasks/main.yml
A few sentences describing the overall goals of the pull request's commits.
- [] TODO
=> AEROGEAR-1970 Add local link lo:0 for linux machines

installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh
use term 'service broker' consistently
=> fix typo in installer messages

Jenkinsfile
Currently we are running only the ansible installation on PR
We should be running basic integration tests as well.
The integration with mobile-cli should suffice. We have changed the mobile-cli job to build the integration tests as a binary and store all of the goldenfiles. This can be then unzipped and run against arbitrary openhsift cluster and we would be running it after the ansible playbooks finish.
Currently we run the tests up to 3 times, in case that the asb is not ready yet.
=> Added running mobile-cli integration tests to mobile-core

docs/walkthroughs/local-setup.adoc
I had problems with running OpenShift on my computer with really low space on HDD. I got NodeUnderDiskPressure.
May be related to this problem with OpenShift https://github.com/openshift/origin/issues/17352
Added node about minimum free space.
=> Added note about reqiured free space

installer/roles/create-mobile-client-crd/files/mobile-client-crd.yaml
CRD no longer matches CRD in mobile-cli repo
Update CRD to match CRD in mobile-repo
=> update CRD properties

installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh
We want to have more recent ASB, preferably the latest stable release.
Changing ASB version to release 1.1.
=> Changing ASB version to 1.1

docs/walkthroughs/provision-keycloak-apb.adoc
[AEROGEAR-2172](https://issues.jboss.org/browse/AEROGEAR-2172)
- Adding info how to provision keycloak service
- Adding info how to bind keycloak service
=> AEROGEAR-2172 Documentation available that explains how keyclok service works

installer/roles/oc-cluster-up/defaults/main.yml
latest, greatest of 3.7x
updting to new release
=> Latest stable release of openshift origin

docs/walkthroughs/developing-apbs-locally.adoc
Adds 3 general considerations for apb development:
* scaling
* labelling
* passwords
Some header indent cleanup too
@maleck13 @aidenkeating @pb82 would you mind reviewing?
=> Add a new section for general APB considerations

installer/requirements.yml
updating to latest version
we are now on 372, and this update uses the same client tools for that
=> Latest version of the client tool, defaulting to v3.7.2

README.adoc, docs/onboarding/demo-videos.adoc, docs/onboarding/onboarding.adoc, docs/walkthroughs/developing-ui-locally.adoc, docs/walkthroughs/local-setup.adoc
Add documentation which contains a list of resources, guides and walkthroughs that will help people get their working environment setup and ready for local development of the UI, CLI and mobile services (via APBs)
=> [AEROGEAR-2397] Add onboarding documentation

docs/onboarding/onboarding.adoc
Add a link for the local UI development guide  to the onboarding doc
=> Add link to UI walkthrough

ui/update_master_config.js
=> working on 3.9.0 installer

docs/walkthroughs/developing-apbs-locally.adoc, docs/walkthroughs/provision-keycloak-apb.adoc
- Update Keycloak docs to reflect recent changes to the bind role
- Update apb development docs to reflect recent changes in labelling for mobile apbs
Related Jira: [AEROGEAR-2376]( https://issues.jboss.org/browse/AEROGEAR-2376)
Dependent on: [AEROGEAR-2421](https://github.com/aerogearcatalog/keycloak-apb/pull/71)
=> Update apb docs

docs/walkthroughs/developing-apbs-locally.adoc
adding two great but short vidoes
ASB intro videos
=> Adding a bit of intro stuff to ASB doc

README.adoc
Update links to templates on aerogear org.
=> Update links to templates

README.adoc
Adds minishift under a common installation heading
Make it simple to see both installation options.
=> update readme to have both ansible and minishift

docs/walkthroughs/installing-mobile-cli.adoc
=> Update CLI installation docs

docs/walkthroughs/create-mobile-client-build.adoc
A documentation describing how to create mobile client builds for android.
=> AEROGEAR-2631 - Add create mobile build documentation.

installer/roles/ansible-service-broker-setup/defaults/main.yml, installer/roles/ansible-service-broker-setup/files/provision-ansible-service-broker.sh, installer/roles/ansible-service-broker-setup/tasks/main.yml
Configure service broker to always pull fresh images
Configure service broker to always pull fresh images
N/A
=> update installer to set image pull policy to always in the broker config

installer/roles/patch-origin-web-console/defaults/main.yml
origin-web-console image was incorrect
Update origin-web-console image
=> Update origin-web-console image

docs/Release.md, docs/walkthroughs/cleaning-up-client-builds.adoc
Adds a doc about how to do a release of an APB or the web console. Also add a doc to show how to clean up a builds and jobs via the OpenShift UI
Based on this card https://trello.com/c/LAJSg5Ni/97-5-as-a-developer-i-want-to-be-able-to-remove-a-build-between-my-mobile-client-and-the-mobile-ci-cd-service-such-that-i-can-clean
=> Aerogear 2585

installer/install.sh
NPM is no longer used, remove it from the install.sh script.
=> Remove npm

docs/walkthroughs/setup-mobile-on-existing-cluster.adoc
Allow users to set up mobile pieces on a cluster they own rather than only being able to use oc cluster up
=> Initial doc for setting up on remote cluster

docs/walkthroughs/mobile-ci-cd-osx-config.adoc
* adds a cocoapods note
* adds osx env var config in jenkins
=> Osx docs update

docs/walkthroughs/self-signed-certs.adoc, installer/playbook.yml, installer/vars/mobile-control-panel.yml
Instructions for reading the openshift cluster cert and installing on client
=> Add doc around using self signed certs on mobile clients

installer/roles/oc-cluster-up/tasks/main.yml
Remove unrequired loopback alias
=> remove loopback alias

installer/install.sh, installer/roles/oc-cluster-up/tasks/main.yml
remove loopback alias and default to local lan ip
=> remove loopback alias and default to local lan ip

installer/requirements.yml
Basically a release of this change (https://github.com/andrewrothstein/ansible-openshift-origin-client-tools/pull/10), to be used before the issue is resolved properly.
@johnfriz Mind taking a look?
=> Fix dependency temporarily

Jenkinsfile
Use CI-RHOS testing cluster for PR check instead of QE AWS one (with verbose mode switched on)
=> Test PR on CI-RHOS cluster

installer/requirements.yml
=> Use AeroGear dependencies

installer/install.sh, installer/roles/oc-cluster-up/defaults/main.yml
Remove the unused property "cluster_local_instance"
ping @johnfriz
=> remove a question from the setup

installer/install.sh
It's currently broken.
@sedroche Mind taking a look?
=> Update OpenShift client check

installer/install.sh
Issue: https://github.com/aerogear/mobile-core/issues/131
* Improve the message
* Add the correct command to upgrade the ansible to the latest version available. 
Following local test.
=> fix(installer): Info message to install Ansible is confusing and not accurate when is required a updated

installer/install.sh
Issue:  https://github.com/aerogear/mobile-core/issues/189
It happens because the oc is not installed and then will be not possible to check the cluster via `oc cluster up`. 
- [] TODO
Following the result faced when the oc tool is not installed yet and will be in the next steps ( when the installation be performed by ansible scripts )
Following the result when the oc tool is already installed.
=> fix(installer): Error when try to check the cluster and oc tool is not installed  yet

installer/roles/provision-mobile-catalog/tasks/main.yml
fix to check if 'failed' is defined as some recent change is causing crash on that now.
removed log
=> fix for undefined, remove debug log

installer/install.sh
ISSUE: https://github.com/aerogear/mobile-core/issues/142
The ansible tasks messages are a not good output in the happy scenarios. Users expected to see just small and useful messages which show the process of the installation, then ansible tasks msg are just useful if the installation fails and is required to debug/troubleshooting it.
Note that messages as `FAIL` and `WARNING` when actually all are OK which make part of the ansible tasks process are not good to be seen as the first contact since the user did not know what actually is happing. Also, if all is fine did not make sense read the ansible output that is not really readable mainly for who did know this product very well.  
* The script is prepared to receive the options params `--debug` and/or `--d`
* If the param `--debug` …
=> Output improvements + debug option param

.github/PULL_REQUEST_TEMPLATE.md
The current template doesn't push the contributor to describe WHAT, WHY, HOW as the steps to check it. 
* More detail information
* Suggestion of PR template
- [] TODO
=> Pull request template improvements

.github/CONTRIBUTING.md
Update contributing guide links
=> Update contribution guide links

installer/install.sh
tidy up text displayed by installer
correct grammar and use redirect urls rather than hard coding for self signed certs docs
=> fix typos and add redirect url
